
package com.sptv.mavenproject2;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuariodelprograma;



/**
 *
 * @author Oficina
 */
public class Administraciondeusuarios extends javax.swing.JFrame {

    /**
     * Creates new form Administraciondeusuarios
     */
    private javax.swing.JTable visor;
    public Administraciondeusuarios() {
        initComponents();
        Mostrar();
        // Inicializa 'visor' y configura su modelo
    
    }
    private void Mostrar() {
    // Definir la consulta JPQL
    String sql = "SELECT u.idusuario, u.nombre FROM Usuariodelprograma u";
    System.out.println(sql);

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("idUsuario");
    model.addColumn("Nombre");

    // Crear una instancia de EntityManager
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("persisventas");
    EntityManager em = emf.createEntityManager();

    try {
        // Ejecutar la consulta
        javax.persistence.Query query = em.createQuery(sql);
        java.util.List<Object[]> results = query.getResultList();

        // Agregar filas al modelo
        for (Object[] row : results) {
            model.addRow(row);
        }

        // Establecer el modelo en la tabla
        tblTabladeusuarios.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e.getMessage());
    } finally {
        em.close();
        emf.close();
    }
}


    public static String generarHash (String input) {
        try {
            // Crear una instancia de MessageDigest para SHA-256
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            
            // Calcular el hash
            byte[] encodedhash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            
            // Convertir el array de bytes a una representación en hexadecimal
            StringBuilder hexString = new StringBuilder(2 * encodedhash.length);
            for (byte b : encodedhash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pfondo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        pTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabladeusuarios = new javax.swing.JTable();
        lblNombre2 = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pswContraseña = new javax.swing.JPasswordField();
        txtID = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnregrsar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pfondo.setBackground(new java.awt.Color(0, 153, 102));

        lblNombre.setText("Nombre del Usuario");

        tblTabladeusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabladeusuarios);

        javax.swing.GroupLayout pTablaLayout = new javax.swing.GroupLayout(pTabla);
        pTabla.setLayout(pTablaLayout);
        pTablaLayout.setHorizontalGroup(
            pTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        pTablaLayout.setVerticalGroup(
            pTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        lblNombre2.setText("Nombre del usuario");

        lblContraseña.setText("Contraseña del Usuario");

        lblIdUsuario.setText("ID del Usuario");

        btnAgregar.setText("Agergar Usuario");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Usuario");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        pswContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContraseñaActionPerformed(evt);
            }
        });

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Administrardor de Usuarios");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnregrsar.setText("regresar");
        btnregrsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregrsarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PfondoLayout = new javax.swing.GroupLayout(Pfondo);
        Pfondo.setLayout(PfondoLayout);
        PfondoLayout.setHorizontalGroup(
            PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PfondoLayout.createSequentialGroup()
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTitulo))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(lblNombre2))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(lblIdUsuario))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PfondoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnregrsar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PfondoLayout.setVerticalGroup(
            PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PfondoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblNombre2))
                .addGap(6, 6, 6)
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseña)
                    .addComponent(lblIdUsuario))
                .addGap(6, 6, 6)
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(pTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregrsar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed

    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Recoger los datos del formulario
    String nombreusuario = txtNombre.getText();
    String contraseña = new String(pswContraseña.getPassword());

// Generar el hash de la contraseña
String hashContraseña = generarHash(contraseña);

// Crear una instancia de Usuariodelprograma con el nombre y la contraseña hasheada
Usuariodelprograma usuario = new Usuariodelprograma(nombreusuario, hashContraseña);

// Obtener una instancia de EntityManager
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("persisventas");
    EntityManager em = emf.createEntityManager();

try {
    // Iniciar una transacción
    em.getTransaction().begin();
    
    // Guardar el usuario en la base de datos
    em.persist(usuario);
    
    // Confirmar la transacción
    em.getTransaction().commit();
    
    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(null, "Usuario guardado exitosamente");
} catch (Exception e) {
    // Si hay algún error, revertir la transacción
    em.getTransaction().rollback();
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error al guardar el usuario: " + e.getMessage());
} finally {
    // Cerrar el EntityManager
    em.close();
    emf.close();
}
        txtNombre.setText("");
    pswContraseña.setText("");
        Mostrar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void pswContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraseñaActionPerformed

    }//GEN-LAST:event_pswContraseñaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
     
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
        // Obtener los datos del formulario
        Long id = Long.parseLong(txtID.getText());
        String nombredeusuario = txtNombre2.getText();

        // Obtener una instancia de EntityManager
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persisventas");
        EntityManager em = emf.createEntityManager();

        try {
            // Iniciar una transacción
            em.getTransaction().begin();

            // Buscar el usuario por ID (Long)
            Usuariodelprograma usuario = em.find(Usuariodelprograma.class, id);
            
            if (usuario != null) {
                // Verificar que el nombre de usuario proporcionado coincide
                if (usuario.getNombre().equals(nombredeusuario)) {
                    // Si el nombre coincide, eliminar el usuario
                    em.remove(usuario);
                    
                    // Confirmar la transacción
                    em.getTransaction().commit();
                    
                    // Mostrar mensaje de éxito
                    JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
                } else {
                    // Si el nombre no coincide, mostrar mensaje de error
                    JOptionPane.showMessageDialog(null, "El nombre de usuario no coincide con el ID proporcionado");
                    em.getTransaction().rollback();
                }
            } else {
                // Si el usuario no existe, mostrar mensaje de error
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                em.getTransaction().rollback();
            }

        } catch (Exception e) {
            // Si ocurre un error, revertir la transacción y mostrar un mensaje de error
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(null, "Error al eliminar el usuario: " + e.getMessage());
        } finally {
            // Cerrar el EntityManager
            em.close();
            emf.close();
        }
    } catch (NumberFormatException e) {
        // Manejar el caso donde el ID no es un número válido
        JOptionPane.showMessageDialog(null, "Por favor, ingresa un ID válido");
    }
            txtID.setText("");
    txtNombre2.setText("");
        Mostrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnregrsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregrsarActionPerformed
        this.dispose();
            
            // Abrir la nueva ventana (PestañaPrincipal)
            PestañaPrincipal nuevaVentana = new PestañaPrincipal();
            nuevaVentana.setVisible(true);
    }//GEN-LAST:event_btnregrsarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administraciondeusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administraciondeusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administraciondeusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administraciondeusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administraciondeusuarios().setVisible(true);
                
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pfondo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnregrsar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pTabla;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTable tblTabladeusuarios;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
