package com.sptv.mavenproject2;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Oficina
 */
public class BuscarporRuc extends javax.swing.JFrame {

    /**
     * Creates new form BuscarporRuc
     */
    public BuscarporRuc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtRuc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTitulo.setText("Ingrese el RUC para buscar");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnregresar.setText("regresar al inicio");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnregresar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnregresar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        
    }//GEN-LAST:event_txtRucActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    // Obtener el RUC ingresado en el campo de texto
    String ruc = txtRuc.getText();
    if (ruc.length() != 11) {
        JOptionPane.showMessageDialog(this, "El RUC debe tener exactamente 11 números.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        return; // Salir del método si la validación falla
    }
    
    // Crear una instancia de EntityManagerFactory y EntityManager
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("persisventas");
    EntityManager em = emf.createEntityManager();
    
    try {
        // Buscar el cliente por RUC
        TypedQuery<Cliente> queryCliente = em.createQuery(
            "SELECT c FROM Cliente c WHERE c.ruc = :ruc", Cliente.class
        );
        queryCliente.setParameter("ruc", ruc);
        Cliente cliente = queryCliente.getSingleResult();

        // Mostrar opciones para ver o editar
        int opcion = JOptionPane.showOptionDialog(this,
            "¿Desea ver o editar los datos del cliente?",
            "Seleccionar opción",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[] {"Ver", "Editar"},
            "Ver"); // El valor por defecto es "Ver"

        if (opcion == JOptionPane.YES_OPTION) {
            // Opción "Ver": Continuar mostrando los detalles del cliente
            // Buscar el libro del cliente
            TypedQuery<Libro> queryLibro = em.createQuery(
                "SELECT l FROM Libro l WHERE l.cliente.ruc = :ruc", Libro.class
            );
            queryLibro.setParameter("ruc", ruc);
            Libro libro = queryLibro.getSingleResult();

            // Buscar la cobranza del cliente
            TypedQuery<Cobranza> queryCobranza = em.createQuery(
                "SELECT co FROM Cobranza co WHERE co.cliente.ruc = :ruc", Cobranza.class
            );
            queryCobranza.setParameter("ruc", ruc);
            Cobranza cobranza = queryCobranza.getSingleResult();

            // Buscar la claveSol del cliente
            TypedQuery<Clavesol> queryClavesol = em.createQuery(
                "SELECT cl FROM Clavesol cl WHERE cl.cliente.ruc = :ruc", Clavesol.class
            );
            queryClavesol.setParameter("ruc", ruc);
            Clavesol clavesol = queryClavesol.getSingleResult();
            
            // Mostrar los detalles del cliente, libro, cobranza y ClaveSol
            JOptionPane.showMessageDialog(this, "Cliente encontrado:\n" +
                "Nombre: " + cliente.getNombre() + "\n" +
                "RUC: " + cliente.getRuc() + "\n" +
                "Correo: " + cliente.getCorreo() + "\n" +
                "Teléfono: " + cliente.getTelefono() + "\n" +
                "ClaveSol Usuario: " + clavesol.getUsuario() + "\n" +
                "Registro de Ventas: " + libro.getRegistrodeventas() + "\n" +
                "Registro de Compras: " + libro.getRegistrodecompras() + "\n" +
                "Diario Simplificado: " + libro.getDiariodeformatosimplificado() + "\n" +
                "Estado Anual: " + (cobranza.getEstadoanual() ? "Al dia" : "Debe") + "\n" +
                "Estado Mensual: " + (cobranza.getEstadomensual() ? "Al dia" : "Debe") + "\n" +
                "Estado Total: " + (cobranza.getEstadototal() ? "Al dia" : "Debe")+"\n" +
                "Fecha de ingreso: "+(cliente.getFechadeingreso())+"\n" +
                "Fecha de primera declaracion: "+(cliente.getPrimeradec())+"\n" +
                "Fecha de Inicio de actividades : "+(cliente.getFechainicioact()),
                "Resultado de búsqueda", JOptionPane.INFORMATION_MESSAGE
            );
        } else if (opcion == JOptionPane.NO_OPTION) {
            // Opción "Editar": Abrir nueva ventana para editar
            Editcliente editCliente = new Editcliente(cliente);
            editCliente.setVisible(true);
            this.setVisible(false);
        }
    } catch (NoResultException e) {
        // Manejar el caso en que no se encuentra el cliente
        JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con el RUC proporcionado.", "Resultado de búsqueda", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Manejar otras excepciones
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al buscar el cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Cerrar el EntityManager y EntityManagerFactory
        em.close();
        emf.close();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        this.dispose();
            
            // Abrir la nueva ventana (PestañaPrincipal)
            PestañaPrincipal nuevaVentana = new PestañaPrincipal();
            nuevaVentana.setVisible(true);
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarporRuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarporRuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarporRuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarporRuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarporRuc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnregresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
