
package com.sptv.mavenproject2;

/**
 * @author Oficina
 */
public class PestañaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PestañaPrincipal
     */
    public PestañaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labTitulo2 = new javax.swing.JLabel();
        labTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnTabladepagos = new javax.swing.JButton();
        btnTabladeclientes = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        labTitulo2.setBackground(new java.awt.Color(255, 204, 51));
        labTitulo2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labTitulo2.setForeground(new java.awt.Color(51, 51, 255));
        labTitulo2.setText("S.A.C");

        labTitulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        labTitulo.setForeground(new java.awt.Color(51, 51, 255));
        labTitulo.setText("CONSULTORIA EMPRESARIAL SERVISERC ");

        btnCerrar.setBackground(new java.awt.Color(0, 255, 102));
        btnCerrar.setText("Cerrar el programa");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnTabladepagos.setBackground(new java.awt.Color(255, 255, 51));
        btnTabladepagos.setText("Tabla de pagos");
        btnTabladepagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabladepagosActionPerformed(evt);
            }
        });

        btnTabladeclientes.setBackground(new java.awt.Color(255, 255, 0));
        btnTabladeclientes.setText("Tabla de clientes");
        btnTabladeclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabladeclientesActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnagregar.setText("Agregar Cliente");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(labTitulo2)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(57, 57, 57)
                .addComponent(btnagregar)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTabladeclientes)
                .addGap(36, 36, 36)
                .addComponent(btnTabladepagos)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labTitulo)
                .addGap(18, 18, 18)
                .addComponent(labTitulo2)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnTabladeclientes)
                    .addComponent(btnTabladepagos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnagregar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.dispose();
            
            // Abrir la nueva ventana (PestañaPrincipal)
        BuscarporRuc nuevaVentana = new BuscarporRuc();
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTabladeclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabladeclientesActionPerformed
        this.dispose();
            
            // Abrir la nueva ventana (PestañaPrincipal)
        Tabladeclientes nuevaVentana = new Tabladeclientes();
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_btnTabladeclientesActionPerformed

    private void btnTabladepagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabladepagosActionPerformed
        this.dispose();
            
            // Abrir la nueva ventana (PestañaPrincipal)
        Tabladedepagos nuevaVentana = new Tabladedepagos();
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_btnTabladepagosActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Addcliente nuevaVentana = new Addcliente();
        nuevaVentana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PestañaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PestañaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PestañaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PestañaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PestañaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnTabladeclientes;
    private javax.swing.JButton btnTabladepagos;
    private javax.swing.JButton btnagregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JLabel labTitulo2;
    // End of variables declaration//GEN-END:variables
}
